# Generated by Django 3.1.4 on 2020-12-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid_Numero', models.CharField(max_length=10)),
                ('cid_Descricao', models.CharField(max_length=255)),
            ],
        ),
    ]
